<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find cob_hardware_config)/robots/raw3-6/urdf/calibration_default.urdf.xacro" />
	<xacro:include filename="$(find cob_calibration_data)/raw3-6/calibration/calibration_offset.urdf.xacro" />>

	<!-- ***************** -->
	<!-- base calibration -->
	<!-- ***************** -->
	<!-- laser front mount positions | relative to base_link -->
    <!--XXX: these parameters e.g. def_laser_front_x are from cob_robots/cob_hardware_config/robots/raw3-5/urdf/calibration_default.urdf.xacro-->
	<xacro:property name="laser_front_x" value="${def_laser_front_x+offset_laser_front_x}"/>
	<xacro:property name="laser_front_y" value="${def_laser_front_y+offset_laser_front_y}"/>
	<xacro:property name="laser_front_z" value="${def_laser_front_z+offset_laser_front_z}"/>
	<xacro:property name="laser_front_roll" value="${def_laser_front_roll+offset_laser_front_roll}"/>
	<xacro:property name="laser_front_pitch" value="${def_laser_front_pitch+offset_laser_front_pitch}"/>
	<xacro:property name="laser_front_yaw" value="${def_laser_front_yaw+offset_laser_front_yaw}"/>

	<!-- laser rear mount positions | relative to base_link -->
	<xacro:property name="laser_rear_x" value="${def_laser_rear_x+offset_laser_rear_x}"/>
	<xacro:property name="laser_rear_y" value="${def_laser_rear_y+offset_laser_rear_y}"/>
	<xacro:property name="laser_rear_z" value="${def_laser_rear_z+offset_laser_rear_z}"/>
	<xacro:property name="laser_rear_roll" value="${def_laser_rear_roll+offset_laser_rear_roll}"/>
	<xacro:property name="laser_rear_pitch" value="${def_laser_rear_pitch+offset_laser_rear_pitch}"/>
	<xacro:property name="laser_rear_yaw" value="${def_laser_rear_yaw+offset_laser_rear_yaw}"/>

	<!-- *********************** -->
	<!-- upper robot calibration -->
	<!-- *********************** -->
	<!-- tower mount positions | relative to base_link -->
	<xacro:property name="tower_x" value="${def_tower_x+offset_tower_x}"/>
	<xacro:property name="tower_y" value="${def_tower_y+offset_tower_y}"/>
	<xacro:property name="tower_z" value="${def_tower_z+offset_tower_z}"/>
	<xacro:property name="tower_roll" value="${def_tower_roll+offset_tower_roll}"/>
	<xacro:property name="tower_pitch" value="${def_tower_pitch+offset_tower_pitch}"/>
	<xacro:property name="tower_yaw" value="${def_tower_yaw+offset_tower_yaw}"/>

	<!-- arm mount positions | relative to base_link -->
	<xacro:property name="arm_x" value="${def_arm_x+offset_arm_x}"/>
	<xacro:property name="arm_y" value="${def_arm_y+offset_arm_y}"/>
	<xacro:property name="arm_z" value="${def_arm_z+offset_arm_z}"/>
	<xacro:property name="arm_roll" value="${def_arm_roll+offset_arm_roll}"/>
	<xacro:property name="arm_pitch" value="${def_arm_pitch+offset_arm_pitch}"/>
	<xacro:property name="arm_yaw" value="${def_arm_yaw+offset_arm_yaw}"/>

	<!-- gripper mount positions | relative to arm_ee_link -->
    <!--directly defined at ./src/cob_robots/cob_hardware_config/robots/raw3-6/urdf/raw3-6.urdf.xacro-->
    <!--<xacro:property name="gripper_x" value="${def_gripper_x+offset_gripper_x}"/>-->
	<!--<xacro:property name="gripper_y" value="${def_gripper_y+offset_gripper_y}"/>-->
	<!--<xacro:property name="gripper_z" value="${def_gripper_z+offset_gripper_z}"/>-->
	<!--<xacro:property name="gripper_roll" value="${def_gripper_roll+offset_gripper_roll}"/>-->
	<!--<xacro:property name="gripper_pitch" value="${def_gripper_pitch+offset_gripper_pitch}"/>-->
	<!--<xacro:property name="gripper_yaw" value="${def_gripper_yaw+offset_gripper_yaw}"/>-->


</robot>
